name: CI/CD Pipeline

on:
    push:
      branches: 
        - 'dev'
    pull_request:
      branches: 
        - 'test' 
        - 'main'
      types: [closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  docker:
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:API"
          push: true
          tags: refentseg/portfolio:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Test
        if: github.ref == 'refs/heads/test'
        run: flyctl deploy --remote-only -a refentse-portfolio-test
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: flyctl deploy --remote-only -a refentse-portfolio-live
